server:
  port: 8084
acme:
  enabled: false
  remote-address: localhost
  security:
    username: zs
    password: 123
    roles:
      - admin
      - user

acmec:
  enabled: false
  remote-address: localhost
  security:
    username: zsf
    password: 111
    roles: [user]

logging:
  level:
    web: debug

validate:
  prop:
    username: zs
    age: 30
    email: zs@sina.com